version: '2.1'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "pk:2:1,influencers:1:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    mockstagram-api:
        image: mockstagram-api
        ports:
            - "3000:3000"
        sysctls:
            - "net.core.somaxconn=2048"
    mockstagram-streamer:
        image: mockstagram-streamer
        ports:
            - "9000-9009:9001"
        environment:
            KAFKA_HOST: ${HOST_IP}:9092
            MOCKSTAGRAM_URL: "http://mockstagram-api:3000/api/v1/influencers/"
            KAFKA_PARTITIONS: 2
        depends_on:
            - mockstagram-api
            - kafka
